import type React from 'react';
import {
  Activity,
  Archive,
  BarChart3,
  Bell,
  Building2,
  CalendarClock,
  ClipboardCheck,
  Clock3,
  CreditCard,
  FileBarChart,
  FileText,
  HandCoins,
  LayoutDashboard,
  Megaphone,
  Menu,
  Package,
  PanelsTopLeft,
  Printer,
  ReceiptText,
  RotateCcw,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Star,
  Store,
  TicketPercent,
  Truck,
  UserCog,
  Users,
  WalletCards,
  Warehouse,
  type LucideProps,
} from 'lucide-react';
import type { AdminIconName } from '@/config/admin-navigation';

const ICONS: Record<AdminIconName, React.ComponentType<LucideProps>> = {
  dashboard: LayoutDashboard,
  bell: Bell,
  orders: ShoppingBag,
  returns: RotateCcw,
  cash: HandCoins,
  shifts: Clock3,
  invoices: FileText,
  shipping: Truck,
  products: Package,
  inventory: Warehouse,
  stocktake: ClipboardCheck,
  barcode: Printer,
  purchasing: Archive,
  suppliers: Building2,
  customers: Users,
  loyalty: Star,
  reviews: Star,
  coupons: TicketPercent,
  campaigns: Megaphone,
  accounting: BarChart3,
  expenses: WalletCards,
  treasury: CreditCard,
  tax: ReceiptText,
  receivables: FileBarChart,
  employees: UserCog,
  attendance: CalendarClock,
  payroll: WalletCards,
  leave: CalendarClock,
  reports: BarChart3,
  'branches-report': Building2,
  content: PanelsTopLeft,
  'store-settings': Store,
  carts: ShoppingBag,
  users: ShieldCheck,
  roles: ShieldCheck,
  branches: Building2,
  settings: Settings,
  audit: Activity,
  backup: Archive,
};

export function AdminIcon({ name, ...props }: { name: AdminIconName } & LucideProps) {
  const Icon = ICONS[name] ?? Menu;
  return <Icon aria-hidden="true" {...props} />;
}

