'use client';

import React, { useMemo, useState } from 'react';
import { useLocale } from 'next-intl';
import { usePathname, useRouter } from '@/i18n/routing';
import { apiFetch } from './ui';
import { Button } from '@/components/ui/foundation';

type Row = { id: string; inventoryId: string; branchId: string; branchName: string; branchNameEn: string; productId: string; nameAr: string; nameEn: string; sku: string; barcode: string | null; category: string; categoryEn: string; brand: string; brandEn: string; stockQuantity: number; lowStockThreshold: number; reorderPoint: number; reorderQuantity: number; suggestedQuantity: number; costPrice: number; estimatedCost: number; requested: boolean; request: { id: string; supplierId: string | null; requestedById: string; requestedAt: string; note: string | null; quantity: number } | null };
type Props = { rows: Row[]; total: number; page: number; totalPages: number; branches: Array<{ id: string; name: string; nameEn: string | null }>; suppliers: Array<{ id: string; name: string }>; filters: { q: string; branch: string; requested: string } };

export default function ReorderClient({ rows, total, page, totalPages, branches, suppliers, filters }: Props) {
  const locale = useLocale(); const router = useRouter(); const pathname = usePathname() || '/admin/reports/reorder'; const isAr = locale === 'ar';
  const [q, setQ] = useState(filters.q); const [branch, setBranch] = useState(filters.branch); const [requested, setRequested] = useState(filters.requested); const [selected, setSelected] = useState<string[]>([]); const [supplierId, setSupplierId] = useState(''); const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const selectedRows = useMemo(() => rows.filter((row) => selected.includes(row.inventoryId)), [rows, selected]);
  const navigate = (nextPage: number) => { const params = new URLSearchParams(); if (q) params.set('q', q); if (branch) params.set('branch', branch); if (requested) params.set('requested', requested); params.set('page', String(nextPage)); router.push(`${pathname}?${params}`); };
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const saveRequests = async () => { if (!selectedRows.length) { setError(isAr ? 'اختر صنفًا' : 'Select an item'); return; } setBusy(true); setError(''); try { await apiFetch('/api/admin/reports/reorder', 'POST', { items: selectedRows.map((row) => ({ branchInventoryId: row.inventoryId, supplierId: supplierId || undefined, quantity: row.suggestedQuantity })), note }); setMessage(isAr ? 'تم تسجيل طلبات النواقص' : 'Reorder requests saved'); setSelected([]); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : (isAr ? 'فشل الحفظ' : 'Save failed')); } finally { setBusy(false); } };
  const createPo = async () => { if (!selectedRows.length) { setError(isAr ? 'اختر صنفًا' : 'Select an item'); return; } if (!supplierId) { setError(isAr ? 'اختر موردًا' : 'Choose a supplier'); return; } const branchIds = new Set(selectedRows.map((row) => row.branchId)); if (branchIds.size !== 1) { setError(isAr ? 'اختر أصناف فرع واحد لإنشاء PO' : 'Select items from one branch'); return; } setBusy(true); setError(''); try { await apiFetch('/api/admin/purchase-orders', 'POST', { intent: 'confirm', supplierId, branchId: [...branchIds][0], notes: note, items: selectedRows.map((row) => ({ productId: row.productId, quantityOrdered: row.suggestedQuantity, unitCost: row.costPrice })) }); setMessage(isAr ? 'تم إنشاء أمر التوريد' : 'Purchase order created'); setSelected([]); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : (isAr ? 'فشل إنشاء PO' : 'PO creation failed')); } finally { setBusy(false); } };
  const updatePolicy = async (row: Row) => { const reorderPoint = window.prompt(isAr ? 'حد إعادة الطلب' : 'Reorder point', String(row.reorderPoint)); if (reorderPoint === null) return; const reorderQuantity = window.prompt(isAr ? 'كمية إعادة الطلب' : 'Reorder quantity', String(row.reorderQuantity)); if (reorderQuantity === null) return; setBusy(true); try { await apiFetch('/api/admin/reports/reorder', 'PATCH', { branchInventoryId: row.inventoryId, reorderPoint: Number(reorderPoint), reorderQuantity: Number(reorderQuantity) }); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : (isAr ? 'فشل الحفظ' : 'Save failed')); } finally { setBusy(false); } };
  const exportCsv = () => { const header = ['sku','barcode','name_ar','name_en','category','brand','branch','stock','reorder_point','suggested','cost','estimated']; const esc = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`; const content = '\uFEFF' + [header.map(esc).join(','), ...rows.map((row) => [row.sku,row.barcode,row.nameAr,row.nameEn,row.category,row.brand,row.branchName,row.stockQuantity,row.reorderPoint,row.suggestedQuantity,row.costPrice,row.estimatedCost].map(esc).join(','))].join('\n'); const url = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'reorder-shortages.csv'; a.click(); URL.revokeObjectURL(url); };

  return <div className="space-y-4">
    <form onSubmit={(e) => { e.preventDefault(); navigate(1); }} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-5 gap-3 text-xs"><div><label className="block font-bold text-slate-400 mb-1">{isAr ? 'بحث' : 'Search'}</label><input value={q} onChange={(e) => setQ(e.target.value)} className="min-h-[44px] w-full rounded-xl border border-slate-700 bg-slate-900 px-2" /></div><div><label className="block font-bold text-slate-400 mb-1">{isAr ? 'الفرع' : 'Branch'}</label><select value={branch} onChange={(e) => setBranch(e.target.value)} className="min-h-[44px] w-full rounded-xl border border-slate-700 bg-slate-900 px-2"><option value="">{isAr ? 'كل الفروع' : 'All branches'}</option>{branches.map((item) => <option key={item.id} value={item.id}>{isAr ? item.name : item.nameEn || item.name}</option>)}</select></div><div><label className="block font-bold text-slate-400 mb-1">{isAr ? 'المتابعة' : 'Follow-up'}</label><select value={requested} onChange={(e) => setRequested(e.target.value)} className="min-h-[44px] w-full rounded-xl border border-slate-700 bg-slate-900 px-2"><option value="">{isAr ? 'الكل' : 'All'}</option><option value="requested">{isAr ? 'مطلوب' : 'Requested'}</option><option value="unrequested">{isAr ? 'غير مطلوب' : 'Not requested'}</option></select></div><div className="flex items-end gap-2"><Button type="submit" variant="primary" className="flex-1">{isAr ? 'تطبيق' : 'Apply'}</Button><button type="button" onClick={exportCsv} className="min-h-[44px] rounded-xl border border-slate-700 px-3 font-bold">CSV</button></div></form>
    <div className="flex flex-wrap items-end gap-2 rounded-2xl border border-blue-500/30 bg-blue-500/10 p-3"><div><label className="block text-[11px] font-bold text-blue-200 mb-1">{isAr ? 'المورد للطلب/PO' : 'Supplier for request/PO'}</label><select value={supplierId} onChange={(e) => setSupplierId(e.target.value)} className="min-h-[44px] rounded-xl border border-slate-700 bg-slate-950 px-2 text-xs"><option value="">{isAr ? 'اختر المورد' : 'Choose supplier'}</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></div><div className="min-w-[220px] flex-1"><label className="block text-[11px] font-bold text-blue-200 mb-1">{isAr ? 'ملاحظة' : 'Note'}</label><input value={note} onChange={(e) => setNote(e.target.value)} className="min-h-[44px] w-full rounded-xl border border-slate-700 bg-slate-950 px-2 text-xs" /></div><Button type="button" onClick={saveRequests} disabled={busy} variant="secondary">{isAr ? 'تم الطلب (تسجيل)' : 'Mark requested'}</Button><Button type="button" onClick={createPo} disabled={busy} variant="primary">{isAr ? 'إنشاء PO من المحدد' : 'Create PO from selected'}</Button></div>
    {message && <p role="status" className="status-success rounded-xl border p-3 text-xs font-bold">{message}</p>}{error && <p role="alert" className="status-danger rounded-xl border p-3 text-xs font-bold">{error}</p>}
    <div className="app-scrollbar app-scrollbar-horizontal overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full min-w-[1200px] text-xs text-start"><thead className="bg-slate-950 text-slate-400"><tr><th className="p-3">{isAr ? 'اختيار' : 'Select'}</th><th className="p-3">{isAr ? 'الصنف' : 'Item'}</th><th className="p-3">{isAr ? 'SKU / باركود' : 'SKU / barcode'}</th><th className="p-3">{isAr ? 'التصنيف / الماركة' : 'Category / brand'}</th><th className="p-3">{isAr ? 'الفرع' : 'Branch'}</th><th className="p-3">{isAr ? 'المخزون' : 'Stock'}</th><th className="p-3">{isAr ? 'حد الطلب' : 'Reorder point'}</th><th className="p-3">{isAr ? 'الكمية المقترحة' : 'Suggested qty'}</th><th className="p-3">{isAr ? 'التكلفة' : 'Cost'}</th><th className="p-3">{isAr ? 'المتابعة' : 'Follow-up'}</th><th className="p-3">{isAr ? 'إجراء' : 'Action'}</th></tr></thead><tbody className="divide-y divide-slate-800">{rows.map((row) => <tr key={row.inventoryId} className="hover:bg-slate-900/60"><td className="p-3"><input type="checkbox" checked={selected.includes(row.inventoryId)} onChange={() => toggle(row.inventoryId)} aria-label={`${isAr ? 'اختر' : 'Select'} ${row.nameAr}`} className="w-5 h-5" /></td><td className="p-3 font-bold text-slate-100">{isAr ? row.nameAr : row.nameEn}<div className="text-[10px] text-slate-500">{isAr ? row.category : row.categoryEn} · {isAr ? row.brand : row.brandEn}</div></td><td className="p-3" dir="ltr">{row.sku}<div className="text-slate-500">{row.barcode || '—'}</div></td><td className="p-3">{isAr ? row.category : row.categoryEn} / {isAr ? row.brand : row.brandEn}</td><td className="p-3">{isAr ? row.branchName : row.branchNameEn}</td><td className="p-3 font-black text-amber-300">{row.stockQuantity}</td><td className="p-3">{row.reorderPoint} / {row.reorderQuantity}</td><td className="p-3 font-bold text-blue-300">{row.suggestedQuantity}</td><td className="p-3">{row.estimatedCost.toFixed(2)}</td><td className="p-3">{row.requested ? <span className="status-success rounded-full border px-2 py-1 text-[10px]">{isAr ? 'تم الطلب' : 'Requested'}</span> : <span className="text-slate-500">{isAr ? 'غير مطلوب' : 'Not requested'}</span>}</td><td className="p-3"><button type="button" onClick={() => updatePolicy(row)} disabled={busy} className="min-h-[44px] rounded-lg border border-slate-700 px-2 font-bold">{isAr ? 'تعديل الحد' : 'Edit policy'}</button></td></tr>)}{rows.length === 0 && <tr><td colSpan={11} className="p-10 text-center text-slate-500">{isAr ? 'لا توجد نواقص' : 'No shortages'}</td></tr>}</tbody></table></div>
    <div className="flex items-center justify-between text-xs text-slate-400"><span>{total} {isAr ? 'صنف' : 'items'}</span><div className="flex gap-2"><button type="button" disabled={page <= 1} onClick={() => navigate(page - 1)} className="min-h-[44px] rounded-xl border border-slate-700 px-3 disabled:opacity-40">{isAr ? 'السابق' : 'Previous'}</button><button type="button" disabled={page >= totalPages} onClick={() => navigate(page + 1)} className="min-h-[44px] rounded-xl border border-slate-700 px-3 disabled:opacity-40">{isAr ? 'التالي' : 'Next'}</button></div></div>
  </div>;
}
